### ISSUE TITLE
Issues with Self-Signed Certs and SoapClient on php >= 5.6

### ISSUE THREAD

**Issue by synack77** [sloan58/uc-insight#1]
Just run this up in lab (awesome work btw).  Had issues with the SQL Query tool not running the queries correctly.  Traced it down to Self Signed certs causing the soapclient to fail.  Had to modify the AxlSoap.php file and add the 'stream_context' line to the SoapClient options:

 $this->client = new SoapClient($wsdlPath,
            [
                'trace'=> true,
                'exceptions'=> true,
                'location' => $location,
                'login' => $user,
                'password' => $pass,
                'stream_context'=> stream_context_create(array('ssl'=>array('verify_peer'=>false, 'verify_peer_name'=>false)))
            ]
        );

This allowed me to connect successfully.

**Comment by sloan58** [comment]
Hey, thanks for checking out the project and for the feedback, it's great to hear.  I added a new field to the 'cluster' configs called 'Verify Peer' that uses the stream context settings that you provided above if unselected.  There's a new migration for that so you can pull the update and run a migration then should be good to go.  Thanks again.
